---
apiVersion: v1
kind: ConfigMap
metadata:
    name: libki-config
    namespace: libki
data:
    LIBKI_DB_DSN: dbi:mysql:libki;host=mariadb.libki.svc.cluster.local;port=3306
    LIBKI_DB_USER: maria-user
    LIBKI_DB_PASSWORD: "pLV03aD!65mt"
    LIBKI_DB_HOST: mariadb.libki.svc.cluster.local
    LIBKI_DB_PORT: "3306"
    LIBKI_DB_DATABASE: libki
    LIBKI_TZ: America/Los_Angeles
    LIBKI_SERVER_PORT: "443"
    LIBKI_MAX_WORKERS: "5"
---
apiVersion: v1
kind: Service
metadata:
    name: libki
    namespace: libki
spec:
    ports:
        - port: 443
    selector:
        app: libki
    clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
    name: libki
    namespace: libki
spec:
    selector:
        matchLabels:
            app: libki
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: libki
        spec:
            containers:
                - name: libki
                  image: enghabu/libki-server:0.4
                  resources:
                      requests:
                          memory: 100Mi
                          cpu: 100m
                      limits:
                          memory: 500Mi
                          cpu: 200m
                  # image: libki/libki-server:latest
                  #   command:
                  #     - ./script/libki_server.pl
                  #   args:
                  #     - -p
                  #     - "443"
                  envFrom:
                      - configMapRef:
                            name: libki-config
                  ports:
                      - containerPort: 443
                        name: libki
---

