apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mariadb
  namespace: libki
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: linuxserver/mariadb
          name: mariadb
          env:
            # Use secret in real usage
            - name: MARIADB_ROOT_PASSWORD
              value: pLV03aD!65mt
            - name: MARIADB_PASSWORD
              value: pLV03aD!65mt
            - name: MARIADB_USER
              value: maria-user
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: MYSQL_ROOT_PASSWORD
              value: pLV03aD!65mt
            - name: TZ
              value: America/Los_Angeles
            # - name: MYSQL_DATABASE
            #   value: USER_DB_NAME #optional
            - name: MYSQL_USER
              value: maria-user #optional
            - name: MYSQL_PASSWORD
              value: pLV03aD!65mt #optional
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mariadb
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 100Mi
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
